# Generated by Django 4.2.27 on 2025-12-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
